apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-hpa
spec: 
# The deployment that the HPA should scale
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-development
  minReplicas: 2
  maxReplicas: 10
  metrics:
# The type of metric to use
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50